### ISSUE TITLE
Project deployment to an inaccessible remote machine fails with NullReferenceException

### ISSUE THREAD

**Issue by arturl** [ms-iot/ntvsiot#32] opened 2015-08-14 23:27 UTC
This only happened once. After that, all attempts produced "Error: Unable to connect to the Microsoft Visual Studio Remote Debugger named '10.125.152.143'", which is good.

I suggest reviewing the code path for potential null-reference issues.

**Comment by munyirik** [comment] 2015-12-04 21:45
@arturl I could not reproduce this so I'm going to close this for now. Please feel free to reopen if you see it again and have repro steps.

**Closed** 2015-12-04 23:36 UTC
Labels: bug
